### ISSUE TITLE
最好能支持web页面编排任务

### ISSUE THREAD

**Issue by sjqzhang** [fieldryand/goflow#13]
如题：最好能支持web页面编排任务，网页提交编排后，可以进行提交，并查看当前进度，这样就很完美了。

**Comment by fieldryand** [comment]
Could you explain more or give some examples? I'm afraid I'm not able to translate well enough to understand.

**Comment by sjqzhang** [comment]
support flow with bpmn specification and use web designer,  [designer](https://github.com/miyuesc/bpmn-process-designer) , No coding required is better.
