### ISSUE TITLE
Question: Can Goflow work without Frontend? 

### ISSUE THREAD

**Issue by shojaeix** [fieldryand/goflow#18]
Hi, 

I'm interested to know if this package can work without any FE. If so, is there any way to get the list of all flows and filter them based on their status?  

Thank you

**Comment by fieldryand** [comment]
Today there is no easy way to do this. But do you really need it without a FE? Or do you want the FE enhanced so you can filter flows by status?

Either way, I'm interested in solving this, just curious what your use case is.

**Comment by shojaeix** [comment]
I like to integrate it into a currently running project, including the dashboard. 

Plus I need to to filter the flows and have some way to monitor the state, so I can raise an alarm or something in case of failure

**Comment by fieldryand** [comment]
Update on this feature--it is planned for v2.0, which should be released in the next few days.

**Comment by fieldryand** [comment]
@shojaeix The API and spec are now available as part of the v2 release.
