### ISSUE TITLE
这里不会有性能问题？

### ISSUE THREAD

**Issue by renjun0106** [fieldryand/goflow#19]
https://github.com/fieldryand/goflow/blob/fd82c0fca35cc5156cb667f722aa0305adb4e152/goflow.go#L116

**Comment by fieldryand** [comment]
No, I don't think that has any performance impact.

If you are seeing performance issues in a Goflow application, especially the browser slowing down, it might be due to a dashboard bug that [was fixed in v1.0.4.](https://github.com/fieldryand/goflow/releases/tag/v1.0.4)
