### ISSUE TITLE
Embed ui static file in one binary file

### ISSUE THREAD

**Issue by zengzhengrong** [fieldryand/goflow#49]
go1.16 has support embed comment,to remove ui file dependency

**Comment by fieldryand** [comment]
Thanks, this is another good idea. I'll include this in the next version.

**Comment by fieldryand** [comment]
I thought about it more. I aim to continue supporting version 2.x.x, and this feature would not be backwards-compatible. More important, as a design decision, the UI should be optional. Therefore at this point I would say no to this change.
