### ISSUE TITLE
UI "Toggle scheduling"   increase the frequency of click，the active icon does not display

### ISSUE THREAD

**Issue by zengzhengrong** [fieldryand/goflow#68]

**Comment by fieldryand** [comment]
I can't reproduce this issue. If I double-click on "Toggle scheduling," the icon appears and disappears (or vice versa) as expected.

**Comment by zengzhengrong** [comment]
More Details，setp by setp 
git clone project and download the latest ui file
```
go run .\example\goflow-example.go
```
Click faster "Toggle scheduling"
![image](https://github.com/fieldryand/goflow/assets/23110784/067728f5-3777-435a-8a30-f9ec457303ab)
![image](https://github.com/fieldryand/goflow/assets/23110784/9594d217-8ce2-4571-9102-0f53c4a9f852)

![image](https://github.com/fieldryand/goflow/assets/23110784/eb4099c7-3acc-4bb8-b298-c2f7e745e51c)

**Comment by fieldryand** [comment]
OK thanks for the hint, I can reproduce it now. I will look into it.
